version: '3.8'

services:
  sellio-feedback:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sellio-feedback
    restart: unless-stopped
    expose:
      - "5005"
    ports:
      - "5005:5005"
    env_file:
      - .env.local
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sellio-feedback.rule=Host(`join.sellioai.com`)"
      - "traefik.http.routers.sellio-feedback.entrypoints=websecure"
      - "traefik.http.routers.sellio-feedback.tls.certresolver=myresolver"
      - "traefik.http.services.sellio-feedback.loadbalancer.server.port=5005"

networks:
  proxy:
    external: true
